/**
 * The die 
 * @author lns18qlr
 *
 */
import java.util.Random;
public class Die {

	private int faceValue; // Current face value of die
	private final int SIDES; // Number of sides
	private Random generator;

	/**
	 * Die constructor
	 * @param s
	 */
	public Die(){
				
		SIDES = 6;
			
		generator = new Random();
		faceValue = generator.nextInt(SIDES) + 1;
	}
	
	/**
	 * ThrowDie generates a new face value for the die
	 */
	 public void throwDie(){
		 faceValue = generator.nextInt(SIDES) + 1;
	 }
	 
	 /**
	  * Returns the face value generated by the random generator
	  * @return integer faceValue
	  */
	public int getFaceValue(){
		return faceValue;
	}
	
	/**
	 * @ return String representation of die
	 */
	public String toString() {
		return getClass().getName() + "Face Value= " + faceValue + " Sides= " + SIDES;
	}
}
